EvidencijaFirmi/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using EvidencijaFirmi.Models;
using System.Diagnostics;

namespace EvidencijaFirmi.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Pocetna()
        {
            return View();
        }

        public IActionResult OServisu() 
        {
            return View();
        }

        public IActionResult PrijavaIliRegistracija()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EvidencijaFirmi/Controllers/NalogController.cs
using AplikacioniSloj;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SlojPodataka;
using System.Data;

public class NalogController : Controller
{
    private readonly clsKorisnikServis _korisnikServis;

    public NalogController(clsKorisnikServis korisnikServis)
    {
        _korisnikServis = korisnikServis;
    }

    [HttpGet]
    public IActionResult Registracija()
    {
        return View();
    }


    [HttpPost]
    public ActionResult Registracija(RegistracijaModel model)
    {
        if (ModelState.IsValid)
        {
            bool uspesnaRegistracija = _korisnikServis.Dodaj(new clsKorisnik
            {
                Jmbg = model.JMBG,
                Ime = model.Ime,
                Prezime = model.Prezime,
                Email = model.Email,
                Lozinka = model.Lozinka
            });

            if (uspesnaRegistracija)
            {
                // Ukoliko je registracija uspešna, preusmeri korisnika na odgovarajući view ili akciju
                return RedirectToAction("Prijava");
            }
            else
            {
                // Ukoliko registracija nije uspela, može se dodati odgovarajuća logika ili poruka
                ModelState.AddModelError(string.Empty, "Registracija nije uspešna. Pokušajte ponovo.");
            }
        }

        // Ako ModelState nije validan, vraća se isti view sa postojećim podacima
        return View(model);
    }

    [HttpGet]
    public ActionResult Prijava()
    {
        return View();
    }
    [HttpPost]
    public ActionResult Prijava(PrijavaModel model)
    {
        if (ModelState.IsValid)
        {
            // Pozovi metodu iz servisa koja proverava korisničke podatke
            var prijavljeniKorisnik = _korisnikServis.PronadjiPoEmail(model.Email);

            if (prijavljeniKorisnik != null)
            {
                // Ako je pronađen korisnik sa datom e-poštom, proveri lozinku
                if (prijavljeniKorisnik.Lozinka == model.Lozinka)
                {
                    // Lozinka je ispravna, postavi korisničke podatke u sesiju
                    HttpContext.Session.SetString("JMBG", prijavljeniKorisnik.Jmbg);
                    HttpContext.Session.SetString("Ime", prijavljeniKorisnik.Ime);
                    HttpContext.Session.SetString("Prezime", prijavljeniKorisnik.Prezime);
                    HttpContext.Session.SetString("Email", prijavljeniKorisnik.Email);
                    HttpContext.Session.SetString("Lozinka", prijavljeniKorisnik.Lozinka);
                    HttpContext.Session.SetString("TipKorisnika", prijavljeniKorisnik.TipKorisnika);

                    // Redirekcija na odgovarajući view u zavisnosti od toga kog tipa je korisnik
                    if (prijavljeniKorisnik.TipKorisnika == "admin")
                    {
                        return RedirectToAction("AdminPocetna", "Admin");
                    }
                    else if (prijavljeniKorisnik.TipKorisnika == "obican_korisnik")
                    {
                        return RedirectToAction("KorisnikPocetna", "Korisnik");
                    }
                }
                else
                {
                    // Pogrešna lozinka
                    ModelState.AddModelError(string.Empty, "Pogrešna lozinka");
                }
            }
            else
            {
                // Nema korisnika sa datom e-mailom
                ModelState.AddModelError(string.Empty, "Nema korisnika u bazi podataka sa navedenim e-mailom!");
            }
        }

        // Ako ModelState nije validan, vraća se isti view sa postojećim podacima
        return View(model);
    }

}

EvidencijaFirmi/Views/Home/OServisu.cshtml
@{
    ViewData["Title"] = "O servisu";
}
<h1 class="display-3">@ViewData["Title"]</h1>

<div class="container-fluid">
<p>
        Naš servis za evidentiranje firmi pruža sveobuhvatno rešenje za registrovanje i upravljanje poslovnim entitetima. 
        S ciljem da vam olakšamo proces registracije i upravljanja firmama, razvili smo sistem koji omogućava efikasno praćenje i upravljanje svim relevantnim informacijama o firmama i njihovim prijavama.
</p>
</div>

EvidencijaFirmi/Views/Home/Pocetna.cshtml
@{
    ViewData["Title"] = "Početna";
}

<div class="text-center">
    <h1>Dobrodošli</h1>
    <h2>Ulogujte se i lako prijavite svoj firmu!</h2>
    <h3>Registrujte se ili prijavite se kako bi ste prijavili Vašu firmu</h3>
    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="PrijavaIliRegistracija"><button class="mojeDuge">PRIJAVI SE</button></a>
</div>

EvidencijaFirmi/Views/Home/PrijavaIliRegistracija.cshtml
@{
    ViewData["Title"] = "Prijava ili registracija";
}

<div class="text-center">
    <h1>Ukoliko već imate nalog prijavite se, a ako ne, registrujte se!</h1>
   <div class="d-inline-flex"> 
       <a class="nav-link text-dark" asp-area="" asp-controller="Nalog" asp-action="Prijava"><button>Prijavi se</button></a>
       <a class="nav-link text-dark" asp-area="" asp-controller="Nalog" asp-action="Registracija"><button>Registruj se</button></a>
    </div>
</div>